kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-nfs-pv-claim
spec:
  storageClassName: nfs-dynamic-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
