apiVersion: v1
kind: Service
metadata:
  name: chart-engine-ui
  namespace: chart-engine
spec:
  ports:
  - port: 8080
  selector:
    app: chart-engine-ui
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chart-engine-ui
  labels:
    app: chart-engine-ui
  namespace: chart-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chart-engine-ui
  template:
    metadata:
      labels:
        app: chart-engine-ui
    spec:
      containers:
      - name: chart-engine-ui
        image: understate/chart-engine-ui:v0.2.0
        ports:
        - containerPort: 8080
      initContainers:
      - name: init-api
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup chart-engine-api; do echo waiting for chart-engine-api; sleep 2; done;']
