apiVersion: v1
kind: PersistentVolume
metadata:
  name: chart-engine-mysql-pv
  labels:
    type: local
  namespace: chart-engine
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/chart-engine/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chart-engine-mysql-pvc
  namespace: chart-engine
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
