kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: chart-engine-mysql-pvc
  namespace: chart-engine
spec:
  storageClassName: nfs-dynamic-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
